config/routes.rb
Rails.application.routes.draw do
  def draw_from_file(routes_file_name)
    instance_eval(File.read(Rails.root.join("config/routing/#{routes_file_name}")))
  end

  scope path: ENV['RAILS_RELATIVE_URL_ROOT'] || '' do

    devise_for :accounts, path: 'auth',
               defaults: { format: :json },
               controllers: {sessions: 'auth/sessions', registrations: 'auth/registrations'}

    devise_scope :accounts do
      get 'create_from_email_message', to: 'auth/sessions#create_from_email_message', as: 'cfem'
    end

    draw_from_file('api/v0/routes.rb')
    draw_from_file('admin/routes.rb')

    #misc
    mount Ckeditor::Engine => '/ckeditor'
  end
end

app/models/ahoy/event.rb
class Ahoy::Event < ApplicationRecord
  include Ahoy::QueryMethods

  self.table_name = "ahoy_events"

  belongs_to :visit
  belongs_to :user, optional: true, class_name: 'Account'
end

app/models/event.rb
class Event < ApplicationRecord
  include DiscussableModel
  include TaskableModel
  belongs_to :created_by, class_name: 'Account'
  belongs_to :event_type
  has_many :event_participants, dependent: :destroy
  has_many :participants, through: :event_participants, source: :participant, class_name: 'Account'
  has_many :documents, as: :document_attachable, dependent: :destroy # class_name: 'Base64Document', as: :base64_doc_attachable,

  accepts_nested_attributes_for :event_participants, allow_destroy: true
  accepts_nested_attributes_for :documents, allow_destroy: true

  scope :available_for_account_as_participant, ->(x) { includes(:event_participants).where(event_participants: { account_id: x }) }
  scope :available_for_account_as_creator, ->(x) { includes(:event_participants).references(:event_participants).where(created_by_id: x) }
  scope :available_for_account, ->(x) { available_for_account_as_creator(x).or(available_for_account_as_participant(x)) }
  scope :default_order, -> { order(created_at: :desc) }

  validates :name, length: { maximum: 200 }, presence: true
  validates :starts_at, :ends_at, :created_by_id, presence: true
  validate :start_less_then_end
  validates :place, length: { maximum: 255 }, if: -> { place.present? }

  before_update :notify_participants_update
  before_create :notify_participants_update, if: -> { available_for_all? }
  before_update :notify_participants_when_set_public
  before_destroy :notify_participants_delete, prepend: true
  #before_save :update_participants_count

  def self.available_accounts_count
    @@available_accounts_count ||= Account.not_blocked.count
  end

  def participants_count
    available_for_all? ? Event.available_accounts_count : super
  end

  def event_participants_list
    available_for_all? ? Account.not_blocked.map { |acc| EventParticipant.new(participant: acc, event: self) } : event_participants
  end

  def update_participants_count!
    update_participants_count
    save!
  end

  private

  def update_participants_count
    self.participants_count = event_participants.count
  end

  def start_less_then_end
    if starts_at && ends_at && starts_at > ends_at
      errors.add(:ends_at, 'Должна быть больше даты начала')
      errors.add(:starts_at, 'Должна быть меньше даты окончания')
    end
  end

  def notify_participants(type)
    EventNotifierWorker.perform_async(participants: event_participants_list.map { |x| x.email&.present? ? x.email : x.participant&.email },
                                      event: as_json(methods: [:changes], include: { event_type: {}, created_by: { methods: [:full_name] } }), type: type)
  end

  def notify_participants_delete
    notify_participants('destroy')
  end

  def notify_participants_update
    notify_participants(new_record? ? 'create' : 'update') if changes.keys.any? { |x| %w[name event_type_id description place starts_at ends_at].include?(x) }
  end

  def notify_participants_when_set_public
    notify_participants('create') if changes.key?('available_for_all') && changes['available_for_all'][1] == true
  end
end

app/models/event_type.rb
class EventType < ApplicationRecord
  has_many :events, dependent: :destroy

  acts_as_tenant :company
end

app/controllers/admin/resources/events_controller.rb
class Admin::Resources::EventsController < Admin::ResourceController
  include Paginatable


  def create
    @resource_instance.created_by_id = current_account.id unless @resource_instance.created_by_id
    super
  end

  def update
    @resource_instance.created_by_id = current_account.id unless @resource_instance.created_by_id
    super
  end

  def index 
    @collection = @collection.includes(:event_type, :created_by)
    super
  end 

  private

  def permitted_attributes
    [
        :id, :name, :created_by_id, :starts_at, :ends_at, :description, :event_type_id, :place, :available_for_all,
        event_participants_attributes: [:id, :account_id, :do_not_disturb, :email, :_destroy],
        documents_attributes: [:id, :name, :file, :remote_file_url, :_destroy]
    ]
  end
end

app/controllers/api/v0/resources/events_controller.rb
class Api::V0::Resources::EventsController < Api::ResourceController
  include Api::V0::Resources::Events

  def index
    render json: @collection.as_json(json_collection_inclusion)
  end

  def show
    render json: @resource_instance.decorate.as_json(json_resource_inclusion)
  end

  def create
    @resource_instance.created_by_id = current_account.id unless @resource_instance.created_by_id
    if @resource_instance.save
      render json: @resource_instance.decorate.as_json(json_resource_inclusion)
    else
      render json: {success: false, errors: @resource_instance.errors.as_json}
    end
  end

  def update
    @resource_instance.created_by_id = current_account.id unless @resource_instance.created_by_id
    if @resource_instance.update_attributes(resource_params)
      render json: @resource_instance.decorate.as_json(json_resource_inclusion)
    else
      render json: {success: false, errors: @resource_instance.errors.as_json}
    end
  end

  private

  def association_chain
    result = resource_collection.includes(chain_collection_inclusion).available_for_account(current_account.id).default_order

    if params[:event_type_id]
      result = result.where(event_type_id: params[:event_type_id])
    end
    if params[:creator_id]
      result = result.where(created_by_id: params[:creator_id])
    end
    if params[:from_time]
      result = result.where('? <= ends_at', Time.parse(params[:from_time]))
    end
    if params[:to_time]
      result = result.where('? <= starts_at', Time.parse(params[:to_time]))
    end
    if params[:in_time]
      result = result.where('? >= starts_at and ? <= ends_at', Time.parse(params[:in_time]), Time.parse(params[:in_time]))
    end
    result.decorate
  end

  def build_resource
    @resource_instance ||= resource_collection.new((action_name == 'create') ? resource_params : {}).decorate
    instance_variable_set("@#{ resource_name }", @resource_instance)
  end

  def permitted_attributes
    [
        :id, :name, :created_by_id, :starts_at, :ends_at, :description, :event_type_id, :place, :available_for_all,
        event_participants_attributes: %i[id email account_id do_not_disturb _destroy],
        documents_attributes:%i[id file remote_file_url name _destroy]
    ]
  end
end

app/controllers/concerns/api/v0/resources/events.rb
module Api::V0::Resources::Events
  extend ActiveSupport::Concern

  included do
    private

    def chain_resource_inclusion
      @chain_resource_inclusion ||= [
        :event_type, :documents, :participants,
        event_participants: [
          participant: [
            default_legal_unit_employee: [position: %i[position department]],
            preferred_email: [], account_emails: []
          ]
        ],
        created_by: [
          default_legal_unit_employee: [position: %i[position department]],
          preferred_email: [], account_emails: []
        ]
      ]
    end

    def chain_collection_inclusion
      @chain_collection_inclusion ||= [
        :event_type, :documents, :participants,
        event_participants: [
          participant: [
            default_legal_unit_employee: [position: %i[position department]],
            preferred_email: [], account_emails: []

          ]
        ],
        created_by: [
          default_legal_unit_employee: [position: %i[position department]],
          preferred_email: [], account_emails: []
        ]
      ]
    end

    def json_collection_inclusion
      @json_collection_inclusion ||= {
        methods: %i[participants_count participants_list created_by],
        include: { event_type: {}, documents: {}, participants: {} }
      }
    end

    def json_resource_inclusion
      @json_resource_inclusion ||= {
        methods: %i[participants_count participants_list created_by],
        include: { event_type: {}, documents: {}, participants: {} }
      }
    end
  end
end

app/views/admin/resources/events/_document_fields.slim
.nested-fields
  .panel
    .panel-body
      .row
        .col-md-10
          .row
            .col-md-12
              = f.hidden_field :id
              = f.input :name, label: 'Название'
              - if f.object&.persisted?
                = link_to f.object&.file&.filename || File.basename(f.object&.file&.url), f.object&.file&.url, target: :_blank
              - else
                = f.file_field :file
        .col-md-1
          = link_to_remove_association f, class: 'btn btn-simple btn-danger button_remove' do
            i.fa.fa-remove

app/views/admin/resources/events/_event_participant_fields.slim
.nested-fields
  .panel
    .panel-body
      .row
        .col-md-11
          .row
            .col-md-12
              = f.input :email, label: 'Email'
          .row
            .col-md-12
              = f.input :account_id, label: 'Сотрудник', collection: Account.all.map {|x| [x&.full_name, x.id]}, include_blank: false, disabled: f.object&.persisted?
        .col-md-1
          = link_to_remove_association f, class: 'btn btn-simple btn-danger button_remove' do
            i.fa.fa-remove

app/views/admin/resources/events/_form.slim
= simple_form_for(@resource_instance) do |f|
  = f.input :name, size: 200, label: 'Название'
  = f.input :description, as: :ckeditor, label: 'Описание'
  = f.input :starts_at, as: :string, size: 20, label: 'Дата начала', input_html: {'data-value': @resource_instance&.starts_at, class: 'datetimepicker-uicker'}
  = f.input :ends_at, as: :string, size: 20, label: 'Дата окончания', input_html: {'data-value': @resource_instance&.ends_at, class: 'datetimepicker-uicker'}
  = f.input :event_type_id, collection: EventType.all.map{|x| [x.name, x.id]}, label: 'Тип события', include_blank: false
  = f.input :place, size: 255, label: 'Место проведения'
  = f.input :available_for_all, as: :boolean, inline_label: true, label: 'Все участники'
  =
  h3 Документы
  #documents.row
    .col-md-7
      = f.simple_fields_for :documents do |d|
        = render 'document_fields', f: d, document: f.object
      .links
        = link_to_add_association 'Добавить', f, :documents, class: 'btn btn-success'
  h3 Участники
  #accounts
    = f.simple_fields_for :event_participants do |ep|
      = render 'event_participant_fields', f: ep, event: f.object
    .links
      = link_to_add_association 'Добавить', f, :event_participants, class: 'btn btn-success'
  p
    - if @resource_instance.new_record?
      = f.submit "Создать событие", class: 'btn btn-info'
    - else
      = f.submit "Обновить", class: 'btn btn-info'
    = link_to "Отмена", events_path, class: 'button'

app/views/admin/resources/events/edit.slim
= resource_page_header("Редактирование события: #{@resource_instance.name}")
= render 'form'

app/views/admin/resources/events/index.slim
h2 Список мероприятий
- if can? :update, resource_class
  p = link_to 'Создать', new_event_path, :class => "btn btn-primary"
table.table
  thead
    tr
      th.col-md-2 = sortable_header 'Название', 'name'
      th.col-md-2 = sortable_header 'Организатор', 'accounts.surname'
      th.col-md-2 = sortable_header 'Дата начала', 'starts_at'
      th.col-md-2 = sortable_header 'Дата завершения', 'ends_at'
      th.col-md-2 = sortable_header 'Тип', 'event_types.name'
      th.col-md-2 Действия
  tbody#index
    - @collection.each do |event|
      tr
        td = link_to event.name, [event]
        td = event&.created_by&.full_name
        td = l(event&.starts_at&.localtime) if event.starts_at
        td = l(event&.ends_at&.localtime) if event.ends_at
        td = event&.event_type&.name
        td
          - if can? :update, event
            = link_to [:edit, event], class: 'btn btn-success btn-simple btn-xs', 'data-toggle': 'tooltip', 'data-original-title': 'Редактировать' do
              i.fa.fa-edit
          - if can? :manage, event
            = link_to [event], method: :delete, class: 'btn btn-danger btn-simple btn-xs button_remove', 'data-toggle': 'tooltip', 'data-original-title': 'Удалить' do
              i.fa.fa-remove
= render 'shared/pagination'

app/views/admin/resources/events/new.slim
= resource_page_header('Создание нового события')
= render 'form'

app/views/admin/resources/events/show.slim
body
  header#content-header
    h1
      | Событие #{@resource_instance.name}
  table.table.table-bordered
    tbody
      tr
        td Название
        td = @resource_instance.name
      tr
        td Описание
        td = @resource_instance&.description&.html_safe
      tr
        td Тип события
        td = @resource_instance&.event_type&.name
      tr
        td Организатор
        td = @resource_instance&.created_by&.full_name
      tr
        td Дата и время начала
        td = l(@resource_instance&.starts_at.in_time_zone('Moscow')) if @resource_instance&.starts_at
      tr
        td Дата и время окончания
        td = l(@resource_instance&.ends_at.in_time_zone('Moscow')) if @resource_instance&.ends_at
      tr
        td Место проведения
        td = @resource_instance.place
      - if @resource_instance.available_for_all
        tr
          td Участники
          td Все
      tr
        td Документы
        td
          ul
            - @resource_instance.documents.each do |d|
              li = link_to d.name || d.file.filename, d.file.url


  - unless @resource_instance.available_for_all
    h2 Участники
    table.table.table-bordered
      thead
        tr
          th ФИО
          th Email
      tbody
        - @resource_instance.event_participants.each do |ep|
          tr
            td = link_to(ep&.participant&.full_name || '', account_path(ep&.participant&.id), target: "_blank") if ep&.participant
            td = mail_to ep.email || ep&.participant&.email

.row
  .col-md-12
    = link_to "Все события", events_path, class: 'btn btn-default'
    - if can? :update, @resource_instance
      = link_to "Редактировать", edit_event_path(@resource_instance), class: 'btn btn-info'
    - if can? :manage, @resource_instance
      = link_to 'Удалить', [@resource_instance], method: :delete, class: 'btn btn-info button_remove'